spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.105.159:3306/kdyl?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  redis:
    database: 1 #redis数据库索引，默认为0
    host: 114.116.105.159 #redis服务器地址
    port: 6379 #redis服务器连接端口
    password: #redis服务器连接密码，默认为null
    timeout: 5000 #redis连接超时时间